// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jfczffsvumptflidnpaz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpmY3pmZnN2dW1wdGZsaWRucGF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyOTU3NzcsImV4cCI6MjA2Nzg3MTc3N30.VwXAEAl9CD-mNDWBJUI0-wAfxWcS7LushPskFg0YSwQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});